# Generated by Django 6.0.2 on 2026-02-21 11:40

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension # <--- Añadido

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(), # <--- ¡ESTO ES LO MÁS IMPORTANTE!
        migrations.CreateModel(
            name='DocumentoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]